Repository CSE112-SP22-TeamXRefactor/CSE112-SP22-TeamXRefactor, pull requests merged in 2022-05, with the labels that each got.

#38 Hotfix tests (works for this month)
  .github/workflows/testing.yml
  source/tests/PuppTests.test.js
Labels: bug

#56 branch solely to fix pupptests and login tests
  package-lock.json
  package.json
  source/Login/LoginJS.js
  source/tests/PuppTests.test.js
Labels: bug, enhancement

#54 Sasha fix js docs
  .github/workflows/docs.yml
  README.md
Labels: documentation

#53 DailyOverViewChange-I17
  source/DailyOverview/DailyJS.js
  source/DailyOverview/DailyOverview.html
  source/DailyOverview/DailyStyles.css
  source/DailyOverview/images/currentDayTestDinos.jpg
  source/DailyOverview/images/house.jpg
  source/tests/PuppTests.test.js
  source/tests/addPhotoTest.test.js
Labels: enhancement, frontend
